Added UserParam class for user parameter specification
lnccbrown/HSSM pull request #579
Opened 2024-08-30 15:48 UTC by digicosmos86

Note: To avoid conflict with `src/jhssm/param.py`, I am naming the directory `src/hssm/param_refactor` for now. Once all integration is tested, I will rename this directory

What was done in this PR:

1. Added a few methods in `prior.py` to prepare for model output
2. Added a UserParam (which will eventually be exported as `hssm.Param`) for users to specify priors and store user specification

2024-08-30 16:32 UTC, AlexanderFengler approved these changes
Prob warrants a comprehensive tutorial on prior setting?
Looks good otherwise.

2024-09-09 20:08 UTC, cpaniaguam requested changes
Looks good. I pointed out a couple of things I would change but might not be needed perhaps due to conventions that I'm not aware of yet.

2024-09-09 20:08 UTC, cpaniaguam commented on tests/test_prior.py
Why not use the truthy/falsy nature of the values in many of these checks? Makes for more consice code.

2024-10-23 00:27 UTC, AlexanderFengler commented
@digicosmos86 is this on hold or pushed through #590 at this point?

2024-10-23 04:36 UTC, AlexanderFengler commented
From what I can see this is redundant now.

2024-10-28 14:44 UTC, closed without merging