Replace Poetry with uv for dependency management and workflows
lnccbrown/HSSM pull request #612
Opened 2024-12-17 17:18 UTC by cpaniaguam

Transition from Poetry to uv for installation and environment setup in GitHub Actions, updating the project configuration accordingly.

2024-12-17 17:28 UTC, AlexanderFengler commented
@cpaniaguam this implies using uv all the way or specific to github workflows?

2025-01-06 16:14 UTC, digicosmos86 requested changes
Looks good! The workflows can be a bit confusing since it both installs UV and system Python and the use of system Python and uv commands are intertwined. To disentangle this, we can do one of the following:

1. Use uv instead of system Python. UV will create a virtual environment with Python installed, and we run all commands with `uv`.
2. Use system Python without using UV. All dependencies are supplied in `pyproject.toml`, so there is no real need for `uv` in github actions.

Personally I think option 1 works a bit better since it replicates our local workflow, and `uv` installs dependencies quite a bit faster.

2025-01-06 16:14 UTC, digicosmos86 commented on .github/setup-env/action.yml
> +      shell: bash
It seems that uv determins the default Python version for the project by using the `.python-version` file in the project root. So I think the above processes can be simplified to:

1. Checkout repo
2. Install UV
3. Create `.python-version` in root directory using Python `inputs.python-version`. (this will require .python-version` to be included in `.gitignore`.
4. Run `uv sync --all-extras` to install all dependencies.

If we are going with the System python route, we don't need `uv`. We can just pip install all dependencies from `pyproject.toml`. Thoguhts?

2025-01-06 16:14 UTC, digicosmos86 commented on .github/workflows/build_and_publish.yml
> +          python -m twine upload dist/*
Since we set up `uv` in the previous step, let's use `uv` for this?

2025-01-06 16:14 UTC, digicosmos86 commented on .github/workflows/build_and_publish.yml
> +        run: mkdocs gh-deploy --force
Instead of `poetry run`, we can just do `uv run`

2025-01-06 16:14 UTC, digicosmos86 commented on pyproject.toml
> +    {name = "Paul Xu", email = "yang_xu@brown.edu"},
@cpaniaguam you can add your name here too

2025-01-10 15:24 UTC, cpaniaguam commented on .github/setup-env/action.yml
> +      shell: bash
I think it'd be simpler to just use the system's python. I was kind of trying to keep the same spirit of the current workflow which does something like this but with Poetry. Additionally, aren't the workflows run with different versions of Python? How could this be done if a single Python version is specified in a file? Currently this is accomplished programmatically within each of the workflows that depend on this `action.yml`.

2025-01-10 15:41 UTC, digicosmos86 commented on .github/setup-env/action.yml
> +      shell: bash
I am fine with either sticking to system Python or using UV to handle everything. The current approach is a mixture of both so can be a bit confusing at times. For example, you run the `Set up Python` step which installs a system Python and now you are using UV to install another version, which is a bit redundant.

If the only issue with using `uv` is how to pin the python version to use for the matrix run, you can run `uv python pin ${{ inputs.python-version }}` to pin the version to be used with the project, and then proceed to run `uv sync` to set up the virtual environment.

I still prefer the uv way because of the many nice functionalities and speed that uv offers. It also replicates our local workflow which is nice. However, if you prefer the system Python way, then let's not include uv in the workflow

2025-01-15 16:22 UTC, digicosmos86 approved these changes
Looks good to me. Just a few minor comments

2025-01-15 16:22 UTC, digicosmos86 commented on .github/setup-env/action.yml
> +      run: uv sync --all-extras
This is my fault. We only need to run `uv sync`. We have an optional dependency group that installs JAX with GPU support, which is unsupported in the dev environment. Let's not install those dependencies.

2025-01-15 16:22 UTC, digicosmos86 commented on .github/workflows/build_and_publish.yml
> +          uv publish --token ${{ secrets.PYPI_TOKEN }}
We still need to publish to testpypi first just to make sure that publishing works

2025-01-15 16:51 UTC, cpaniaguam commented on .github/workflows/build_and_publish.yml
> +          uv publish --token ${{ secrets.PYPI_TOKEN }}
It's not clear to me how to do this with `uv` or whether it supports this. For now I could keep this part of the workflow using poetry. Thoughts?

2025-01-15 16:57 UTC, digicosmos86 commented on .github/workflows/build_and_publish.yml
> +          uv publish --token ${{ secrets.PYPI_TOKEN }}
Seems to me this should not be difficult. This is their documentation on adding a different index than PyPI:

https://docs.astral.sh/uv/guides/publish/#building-your-package

Let me know if there's further issues

2025-01-22 04:33 UTC, AlexanderFengler approved these changes
lgtm.

2025-01-22 13:10 UTC, merged